# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cc64e74cba8f6ce24463bb3910ddb555"
name = "Company Registration"
handle = "company-registration"
application_url = "https://consequences-survey-supplements-food.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes ="read_products,write_products,read_orders"

[auth]
redirect_urls = ["https://consequences-survey-supplements-food.trycloudflare.com/auth/callback", "https://consequences-survey-supplements-food.trycloudflare.com/auth/shopify/callback", "https://consequences-survey-supplements-food.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
